apiVersion: v1
kind: Service
metadata:
    name: frontend-service
    namespace: stackforge
    labels:
        app: frontend
        tier: frontend
spec:
    type: NodePort
    selector:
        app: frontend
        tier: frontend
    ports:
        - protocol: TCP
          port: 80
          targetPort: 80
          nodePort: 30080
          name: http
