apiVersion: v1
kind: Secret
metadata:
    name: stackforge-secret
    namespace: stackforge
type: Opaque
stringData:
    SUPABASE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJhdm5samJ0ZG1oZWFhaG13bnZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAwOTgxMDAsImV4cCI6MjA4NTY3NDEwMH0.xOYw--5efwvDl3KYLm25nkfK5QAGowgjMDAXsVZW0ZU
    SUPABASE_URL: https://bavnljbtdmheaahmwnva.supabase.co
    JWT_SECRET: your_super_secret_jwt_key
    PORT: "3000"
    NODE_ENV: development
    FRONTEND_URL: http://localhost:5173
    VITE_API_URL: http://localhost:3000/api